import type { Metadata } from "next";
import { ThemeProvider } from "./Components/ThemeProvider";
import "./globals.css";
import { Roboto_Condensed } from 'next/font/google'

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-condensed',
})



export const metadata: Metadata = {
  title: "Chandan Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoCondensed.variable} antialiased cz-shortcut-listen="true"`}
      >
        <ThemeProvider
          attribute="class" // 👈 this will manage `class="dark"` on `<html>`
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

