import type { Metadata } from "next";
import { ThemeProvider } from "./Components/ThemeProvider";
import "./globals.css";
import { Roboto_Condensed } from 'next/font/google'
import ScrollToTopButton from "@/components/ui/ScrollToTopButton";
import { Toaster } from "react-hot-toast";

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-condensed',
})

export const metadata: Metadata = {
  title: "Chandan Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoCondensed.variable} antialiased cz-shortcut-listen="true overflow-hidden"`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster position="bottom-center" />
          <ScrollToTopButton/>
        </ThemeProvider>
      </body>
    </html>
  );
}

